var mongoose = require("mongoose");
var Schema = mongoose.Schema;

var PremixColoringSchema = new Schema({
  AGrecipe: Number,
  AGval: Number,
  backtubed: Number,
  batch: String,
  botlabel: String,
  botlabelsku: String,
  botSKU: String,
  bottles: Number,
  boxname: { name: String, sku: String },
  brand: String,
  branded: Number,
  brandSKU: String,
  bsize: Number,
  btype: String,
  CBDrecipe: Number,
  CBDvalue: Number,
  coloredpremix: Number,
  Color: { name: String, sku: String, val: Number },
  CompletionDate: Number,
  customer: String,
  customerSKU: String,
  dateshipped: Number,
  fill: Number,
  final_status: String,
  flavour: { name: String, sku: String },
  flavrecipe: Number,
  flavvalue: Number,
  labeling_status: String,
  lid: String,
  lidSKU: String,
  MCTrecipe: String,
  MCTval: String,
  mixing: Number,
  mixing_status: String,
  NIB: String,
  NICO: Number,
  Nicotrecipe: Number,
  Nicotrecipesalts: Number,
  orderdate: Number,
  orderID: String,
  packaging_status: String,
  packagingType: {
    name: String,
    sku: String
  },
  packlabel: String,
  packlabelsku: String,
  partialPackaging: Number,
  partialProduction: Number,
  PGrecipe: Number,
  PGval: Number,
  ppb: Boolean,
  ppp: Boolean,
  premixed: Number,
  printing_status: String,
  premixSKU: String,
  premixSKUColored: String,
  premixdescr: String,
  premixdescrColored: String,
  priority: Number,
  productcode: String,
  productdescription: String,
  production_status: String,
  QTY: Number,
  recipe: {
    id: Number,
    name: String,
    Color: {
      name: String,
      sku: String,
      val: Number
    }
  },
  removedPackaging: Number,
  removedProduction: Number,
  row: Number,
  runtime: Number,
  saved: Boolean,
  shipping_status: String,
  SHIPPINGCODE: String,
  stocking: Number,
  unbranded: Number,
  userset: Boolean,
  VGrecipe: Number,
  VGval: Number,
  wentNegative: Boolean
});

module.exports = mongoose.model("PremixColoring", PremixColoringSchema);
